name: human_guided_abstractions
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pip
- ipython
- torchvision
- pip:
  - certifi==2022.9.24
  - charset-normalizer==2.1.1
  - contourpy==1.0.5
  - cycler==0.11.0
  - fonttools==4.38.0
  - idna==3.4
  - joblib==1.2.0
  - kiwisolver==1.4.4
  - matplotlib==3.6.1
  - numpy==1.23.4
  - packaging==21.3
  - pandas==1.5.2
  - Pillow==9.2.0
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - pyyaml==6.0
  - requests==2.28.1
  - scikit-learn==1.1.2
  - scipy==1.9.3
  - six==1.16.0
  - threadpoolctl==3.1.0
  - torch==1.12.1
  - torchvision==0.13.1
  - typing_extensions==4.4.0
  - urllib3==1.26.12